Update pipeline.yml

diff --git a/.buildkite/pipeline.yml b/.buildkite/pipeline.yml
--- a/.buildkite/pipeline.yml
+++ b/.buildkite/pipeline.yml
@@ -1,16 +1,14 @@
 steps:
   - label: "Failing Step"
-    commands:
-      - echo "EXIT_CODE=3" >> "$BUILDKITE_ENV_FILE"
-      - exit 3
+    soft_fail: true
+    command: |
+      echo "EXIT_CODE=3" >> "$BUILDKITE_ENV_FILE"
+      exit 3  # Step fails, but pipeline continues
 
   - label: "Trigger if EXIT_CODE=3"
-    depends_on: []
-    allow_dependency_failure: true
     command: |
-      echo "Current EXIT_CODE value: $EXIT_CODE"
       if [ "$EXIT_CODE" = "3" ]; then
         echo 'steps:
           - label: "Triggered pipeline"
-            trigger: "training-1/starter-pipeline-2"' | buildkite-agent pipeline upload
+            trigger: "training/starter-pipeline-2"' | buildkite-agent pipeline upload
       fi
